[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  DEPLOY_TIMESTAMP = "2025-08-21-12:20"
  BUILD_VERSION = "v2.1-netlify-ci"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
